import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import Ajv from 'ajv/dist/2020.js';import {evaluateCoordination,evaluateOutcome} from '../skills/woia-operations/scripts/coordination-gate.mjs';
const good={department:"operations",organization:'synthetic-org',actor:'staff',purpose:'bounded-coordination',subject_ref:'provider:subject',subject_version:'v1',operation_id:'op-1',policy_version:'p1',source_map_version:'s1',operation:'prepare',access_authenticated:true,access_authorized:true,source_status:'ACCEPTED_CURRENT',authority_status:'EFFECTIVE',authority_version:'v1',effect_status:'NONE',evidence_refs:['document:v1']};
good.grant=Object.fromEntries(['organization','actor','purpose','subject_ref','subject_version','operation'].map(k=>[k,good[k]]));
test('accepted scoped preparation has no dispatch or business write',()=>{const r=evaluateCoordination(good);assert.equal(r.result,'PASS');assert.equal(r.dispatch,false);assert.equal(r.business_fact_written,false)});
for(const [key,value] of Object.entries({department:'other',organization:'',actor:'',purpose:'',subject_ref:'',subject_version:'',operation_id:'',policy_version:'',source_map_version:'',access_authenticated:false,access_authorized:false,source_status:'UNKNOWN',authority_status:'REVOKED',authority_version:'v2',effect_status:'UNKNOWN',evidence_refs:[],operation:'send',external_contact:true,scheduling_mutation:true,financial_effect:true,autonomous_negotiation:true,business_fact_write:true}))test('fails closed '+key,()=>assert.equal(evaluateCoordination({...good,[key]:value}).result,'BLOCKED'));
test('stale and conflicting sources stay blocked',()=>{for(const source_status of ['STALE','CONFLICTING','INFERRED'])assert.equal(evaluateCoordination({...good,source_status}).result,'BLOCKED')});
test('unaccepted receiver and unavailable transport block',()=>assert.equal(evaluateCoordination({...good,operation:'request-contribution',grant:{...good.grant,operation:'request-contribution'},receiver:'finance',core_transport:'UNAVAILABLE'}).result,'BLOCKED'));
test('qualified contribution request retains separate receiver',()=>assert.equal(evaluateCoordination({...good,operation:'request-contribution',grant:{...good.grant,operation:'request-contribution'},receiver:'operations',core_transport:'QUALIFIED'}).result,'PASS'));
test('receipt is not competent acceptance',()=>assert.equal(evaluateCoordination({...good,operation:'record-contribution',grant:{...good.grant,operation:'record-contribution'},receiver_acceptance:'RECEIVED',correlation_id:'r1',contribution_status:'EVIDENCED'}).result,'BLOCKED'));
test('completion cannot erase residuals',()=>{assert.equal(evaluateCoordination({...good,operation:'close-contribution',grant:{...good.grant,operation:'close-contribution'},competent_acceptance:'ACCEPTED',fulfillment:'EVIDENCED',residuals:[{}]}).result,'BLOCKED');assert.equal(evaluateCoordination({...good,operation:'close-contribution',grant:{...good.grant,operation:'close-contribution'},competent_acceptance:'ACCEPTED',fulfillment:'EVIDENCED',residuals:[{owner:'finance',next_action:'reconcile'}]}).result,'PASS')});
test('schema accepts scoped input and rejects wrong department',()=>{const schema=JSON.parse(fs.readFileSync(new URL('../skills/woia-operations/references/coordination-input.schema.json',import.meta.url)));const v=new Ajv().compile(schema);assert.equal(v(good),true);assert.equal(v({...good,department:'other'}),false)});
test('method is five-part generic root with hard Core dependency',()=>{const m=JSON.parse(fs.readFileSync(new URL('../skills/woia-operations/references/method.json',import.meta.url)));const d=JSON.parse(fs.readFileSync(new URL('../dev.woia/manifest.json',import.meta.url)));assert.equal(m.method.length,5);assert.equal(d.schema,'dev.woia.department-orchestrator/v1');assert.equal(d.requires_plugins[0].minimum_version,'0.5.3');assert.equal(m.production_ready,false)});

for(const key of ['organization','actor','purpose','subject_ref','subject_version','operation'])test('rejects grant mismatch '+key,()=>assert.equal(evaluateCoordination({...good,grant:{...good.grant,[key]:'other'}}).result,'BLOCKED'));
const outcomes={"field_preparation":["access_permission","resource_readiness"],"field_result":["human_report","original_evidence","verification_scope"],"physical_transfer":["custody_evidence","competent_acceptance"]};
for(const [phase,keys] of Object.entries(outcomes)){const facts=Object.fromEntries(keys.map(k=>[k,{status:'ACCEPTED',evidence_ref:'source:'+k,version:'v1'}]));test('independent '+phase+' evidence never accepts business fact',()=>{const r=evaluateOutcome(phase,facts);assert.equal(r.result,'EVIDENCE_READY_FOR_OWNER_REVIEW');assert.equal(r.accepted_business_fact,false)});for(const key of keys)test(phase+' requires independent '+key,()=>assert.equal(evaluateOutcome(phase,{...facts,[key]:{status:'UNKNOWN'}}).result,'BLOCKED'));}
test('unsupported outcome cannot be inferred',()=>assert.equal(evaluateOutcome('all-done',{}).result,'BLOCKED'));

test('malformed evidence is blocked rather than throwing',()=>assert.equal(evaluateCoordination({...good,evidence_refs:'document:v1'}).result,'BLOCKED'));
